<div class="footer-box-bize">
    <div class="title-bize">BIZE ULASIN</div>
    <div class="contact">
        <div class="telephone">
            <div class="image-bize">
                <img class="image-telephone" src=<?php echo $this->getViewFileUrl('images/item17.png'); ?> >
            </div>
            <div class="telephone-number">0212 000 00 00</div>
            <div class="name-branch">Pazartesi - Cuma</div>
            <div class="timework">09:00 - 18:00</div>
        </div>

        <div class="email-bize">
            <div class="image-bize">
            <img class="image-letter" src=<?php echo $this->getViewFileUrl('images/item18.png'); ?> >
            </div>
            <div class="notice-email">Bize mail atin</div>
        </div>
    </div>



    <div class="box-review"></div>

    <div class="box-moreinfo">
        <div class="footer-dropdown">
            <hr>
            <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
            <ul class="item-dropdown">
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
            </ul>
            <hr>
        </div>

        <div class="footer-dropdown">
            <hr>
            <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
            <ul class="item-dropdown">
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
                <li>Sikca Sorulan Sorular</li>
            </ul>
            <hr>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function($){
            jQuery(document).ready( function() {
                $('.item-dropdown').slideUp();
                $('.name-dropdown').click(function(event) {
                    /* Act on the event */
                    console.log('ok')
                    $('.item-dropdown').slideUp();
                    $(this).toggleClass('xanh');

                    //khi click thì nội dung hiện ra
                    $(this).next().slideToggle(1000,"easeOutExpo");

                    //để khi clik vào nội dung sổ xuống đồng thời body cũng trươt lên 1 đoạn
                    $('html,body').animate({scrollTop:$(this).offset().top})
                });
            });
        });
    </script>
</div>
