<?php /**@var $block \Magento\Theme\Block\Html\Footer*/ ?>
<div class="footer-box-bize">
    <div class="title-bize">BIZE ULASIN</div>
    <div class="contact">
        <div class="telephone">
            <div class="image-bize">
                <img class="image-telephone" src=<?php echo $this->getViewFileUrl('images/item17.png'); ?> >
            </div>
            <div class="telephone-number">0212 000 00 00</div>
            <div class="name-branch">Pazartesi - Cuma</div>
            <div class="timework">09:00 - 18:00</div>
        </div>

        <div class="email-bize">
            <div class="image-bize">
            <img class="image-letter" src=<?php echo $this->getViewFileUrl('images/item18.png'); ?> >
            </div>
            <div class="notice-email">Bize mail atin</div>
        </div>
    </div>
</div> <!-- end footer-box-bize -->


    <div class="box-review"></div><!--  end box-review -->


<div class="box-moreinfo">
    <div class="footer-dropdown">
        <hr>
        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>

    <div class="footer-dropdown">

        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>

    <div class="footer-dropdown">

        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>

    <div class="footer-dropdown">

        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>

    <div class="footer-dropdown">

        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>

    <div class="footer-dropdown">

        <div class="name-dropdown">YARDIM VE DESTEK <span id="sign-dropdown">&#8964;</span></div>
        <ul class="item-dropdown">
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
            <li>Sikca Sorulan Sorular</li>
        </ul>
        <hr>
    </div>


</div> <!-- end box-moreinfo -->
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        jQuery(document).ready( function() {
            $('.item-dropdown').slideUp();
            $('.name-dropdown').click(function(event) {
                /* Act on the event */
                // console.log('ok')
                // $('.item-dropdown').slideUp();
                // $('.name-dropdown').removeClass('change-background');
                // $(this).toggleClass('change-background');

                //khi click thì nội dung hiện ra
                $(this).next().slideToggle(1000,"easeOutExpo");

                //để khi clik vào nội dung sổ xuống đồng thời body cũng trươt lên 1 đoạn
                // $('html,body').animate({scrollTop:$(this).offset().top})
            });
        });
    });
</script>
    <div class="select-lorem">
        <div class="select-lorem-box">
            <div class="select-lorem-title">LOREM IPSUM</div>
            <ul class="lorem-ipsum">
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Aebeab at</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Curabitur faucibus</li>
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Nam dapibus</li>
                <li>Aebeab at</li>
            </ul>
        </div>

        <div class="select-lorem-box">
            <div class="select-lorem-title">LOREM IPSUM</div>
            <ul class="lorem-ipsum">
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Aebeab at</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Curabitur faucibus</li>
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Nam dapibus</li>
                <li>Aebeab at</li>
            </ul>
        </div>

        <div class="select-lorem-box">
            <div class="select-lorem-title">LOREM IPSUM</div>
            <ul class="lorem-ipsum">
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Aebeab at</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Curabitur faucibus</li>
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Nam dapibus</li>
                <li>Aebeab at</li>
            </ul>
        </div>

        <div class="select-lorem-box">
            <div class="select-lorem-title">LOREM IPSUM</div>
            <ul class="lorem-ipsum">
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Aebeab at</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Curabitur faucibus</li>
                <li>Nam dapibus</li>
                <li>Mauris non risus</li>
                <li>Integer imperdiet</li>
                <li>Nulla id tortor</li>
                <li>Nam dapibus</li>
                <li>Aebeab at</li>
            </ul>
        </div>

    </div><!--  end select lorem -->


<div class="country-edin">
<?= $block->getChildHtml('select_language', false); ?>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function($){
            jQuery(document).ready( function() {
                $('.selected').click(function(event) {

                    $('ul#country-drop').slideToggle();
                });

                $('ul#country-drop li .one-country').click(function(event) {

                    var a = $(this).html();
                    console.log(a);
                    $('.selected').html(a +"<i class=\"fas fa-caret-down\"></i>" );
                    $('ul#country-drop').slideUp();
                });
            });
        });
    </script>

<div class="takip-edin">
        <div class="takip-title">Bizi takip edin</div>
        <img  src="<?php echo $this->getViewFileUrl('images/item21.png'); ?>" alt="">
 </div> <!-- end takip-edin -->
</div>


<hr>

<div class="partner-logo-mobile">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo1.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo2.png'); ?>" alt="">
</div>

<div class="partner-logo-desktop">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/GIA_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/HRD_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/VISA_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/MASTERCARD_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/MAESTRO_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/AMERICANEXPRESS_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/PAYPAL_black.png'); ?>" alt="">
    <img  src="<?php echo $this->getViewFileUrl('images/partner-logo/PAYMENTMETHODS_black.png'); ?>" alt="">
</div>
<div class="copyright">
    Copyright © 2018 GALAPEL. All rights reserved.
</div>

