<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */
?>

<div class="country-takip">
<div class="country">
    <div class="image-world">
        <img  src=<?php echo $this->getViewFileUrl('images/item20.png'); ?>>
    </div>


    <?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="country-select" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <div class="title-country-select">Ulkenize Secin</div>
       
        <div class="selected"> <i class="fas fa-caret-down"></i>
           <!--  <img src=<?php echo $this->getViewFileUrl('images/item19.png'); ?>> -->
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getName() == $block->getStoreName()): ?>
                                <img src=<?php echo $this->getViewFileUrl("images/{$_lang->getCode()}.png"); ?>>
                    <?php endif; ?>
                <?php endforeach; ?>
                    <span class="name-country"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </div>

            <div class="dropdown">
                 <ul id="country-drop" style="display: none">
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <li>
                            <div class="one-country">
                                <img src=<?php echo $this->getViewFileUrl("images/{$_lang->getCode()}.png"); ?>>
                                <span class="name-country">
                                    <a  href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                                </span>
                                
                            </div>
                            
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            </div>
           
        </div>
</div>
    
    </div>
<?php endif; ?>

